version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: foodfront:latest
    container_name: foodfront
    restart: unless-stopped
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.foodfront.tls=true"
      - "traefik.http.routers.foodfront.tls.options=default"
      - "traefik.http.routers.foodfront.tls.certresolver=letsEncrypt"
      - "traefik.http.routers.foodfront.rule=Host(`food.se.215sozvezdie.ru`)"
      - "traefik.http.services.foodfront.loadbalancer.server.port=80"
      - "traefik.http.routers.foodfront.entryPoints=http,https"
      - "traefik.docker.network=traefik"
    environment:
      - NODE_ENV=production

networks:
  traefik:
    external: true

